-- ============================================================
-- GUARDVETO — Retirer les deux tables de sauvegarde du 4 août
-- ============================================================
-- CE QUE ÇA CORRIGE. Les deux seules erreurs rouges du Security Advisor
-- Supabase, signalées par MiKL le 2026-08-25 :
--
--   public._backup_creneau_modele_20260804    RLS désactivée, 0 politique, 8 lignes
--   public._backup_relation_creneau_20260804  RLS désactivée, 0 politique, 5 lignes
--
-- Ce sont des copies prises le 4 août pendant la migration « socle + affinage
-- par période type » (`fedf3df`). Elles ont servi de filet le jour J et
-- n'ont jamais été retirées.
--
-- POURQUOI C'ÉTAIT UN PROBLÈME. Une table du schéma `public` sans RLS est
-- lisible par le rôle `anon`, et la clé anon vit dans le code du navigateur :
-- n'importe qui pouvait les lire par appel REST direct, sans être connecté.
-- C'est le mécanisme exact de l'incident des vues `security_invoker` du
-- 22/08, en beaucoup moins grave — ici le contenu est de la configuration de
-- créneaux, pas des données personnelles ni un planning nominatif.
--
-- POURQUOI ON SUPPRIME PLUTÔT QUE DE POSER UNE RLS. Poser une politique
-- reviendrait à sécuriser un objet dont personne n'a l'usage : aucun code du
-- produit ne lit ces deux tables (vérifié par recherche sur `_backup_` dans
-- `src/` et `supabase/`), et une sauvegarde de trois semaines qu'on ne relit
-- pas n'est plus une sauvegarde. La bonne fermeture d'une porte inutile est
-- de retirer la porte.
--
-- ── CE QUE LE CONTENU CONTENAIT EXACTEMENT, vérifié avant suppression ──────
--
-- On ne supprime pas une sauvegarde sur la foi de son nom. Les 13 lignes ont
-- été inventoriées et confrontées aux tables vivantes le 2026-08-25 :
--
--   _backup_creneau_modele    : 8 lignes — 4 encore présentes à l'identique
--                               dans `creneau_modele`, 4 disparues
--   _backup_relation_creneau  : 5 lignes — 3 encore présentes dans
--                               `relation_creneau`, 2 disparues
--
-- Les 6 lignes disparues appartenaient TOUTES au profil de planning
-- `b7990ef3-1c06-4f2f-8308-256974192ae8` — un profil qui **n'existe plus** :
-- elles sont mortes avec lui, ce qui est le comportement attendu (les créneaux
-- appartiennent à leur profil). Le profil survivant,
-- `4d5e5444-06bf-4c55-bf2f-6732486d6aa4` (« Configuration standard »), a bien
-- ses créneaux et ses relations dans les tables vivantes.
--
-- **Rien n'est donc perdu** : le contenu est soit redondant avec le vivant,
-- soit orphelin d'un profil supprimé. C'est la vérification qui autorise la
-- suppression, pas l'ancienneté du fichier.
--
-- ⚠️ IRRÉVERSIBLE malgré tout. La structure reste reconstructible :
-- `creneau_modele` et `relation_creneau` existent toujours, ce sont les tables
-- vivantes dont ces deux-là étaient la photo.
-- ============================================================

drop table if exists public._backup_creneau_modele_20260804;
drop table if exists public._backup_relation_creneau_20260804;
